include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    lines_longer_than_80_chars: ignore
    unintended_html_in_doc_comment: ignore
