name: animated_emoji
description: "Show beautiful, customizable animated emojis using Noto Animated Emoji"
version: 1.0.1+1
homepage: https://github.com/RoundedInfinity/animated_emoji

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

screenshots:
  - description: "🚀 An animated rocket"
    path: example/screenshots/rocket.webp
