name: animated_emoji
description: "Show beautiful, customizable animated emojis using Noto Animated Emoji"
version: 3.2.1
repository: https://github.com/RoundedInfinity/animated_emoji
issue_tracker: https://github.com/RoundedInfinity/animated_emoji/issues

topics:
  - emoji
  - emojis
  - animated
  - lottie
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

screenshots:
  - description: "🚀 An animated rocket"
    path: example/screenshots/rocket.webp
